name: productivity_app

description: "Productivity App - Final Year Project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  cunning_document_scanner:
  flutter_dnd:
  flutter_riverpod:
  flutter_switch:
  flutter_inset_box_shadow:
  fl_chart:
  curved_navigation_bar:
  hive_flutter:
  flutter_slidable:
  flutter_heatmap_calendar:
  gap:
  intl:
  google_fonts:
  flutter_colorpicker:
  shared_preferences:
  animated_snack_bar:
  google_generative_ai:
  table_calendar:
  image_picker: 
  image: 
  permission_handler: 
  pdf: 
  media_scanner: 
  external_path: 
  path_provider:
  camera:
  image_gallery_saver:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/