name: fyp
description: FYP

publish_to: "none"

version: 1.5.0+40

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  path: ^1.9.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  iconsax: ^0.0.8
  timezone: ^0.9.3
  workmanager: ^0.5.2
  home_widget: ^0.5.0
  file_picker: ^8.0.3
  restart_app: ^1.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  time_machine: ^0.9.17
  bottom_picker: ^2.7.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.3
  table_calendar: ^3.0.9
  flutter_timezone: ^1.0.8
  package_info_plus: ^8.0.0
  flex_color_picker: ^3.4.1
  isar_flutter_libs: ^3.1.0+1
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.1.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  flutter_dnd: ^0.1.4+1
  flutter_switch: ^0.3.2
  flutter_inset_box_shadow: ^1.0.8
  hive_flutter: ^1.1.0
  flutter_slidable: ^3.1.0
  flutter_heatmap_calendar: ^1.0.5
  shared_preferences: ^2.2.3
  animated_snack_bar: ^0.4.0
  google_generative_ai: ^0.4.0
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.3+1
  image_picker: ^1.1.1
  hive: ^2.2.3
  pedometer: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
