name: fyp
description: FYP

publish_to: "none"

version: 1.5.0+40

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  path: ^1.9.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  iconsax: ^0.0.8
  timezone: ^0.9.3
  workmanager: ^0.5.2
  home_widget: ^0.5.0
  file_picker: ^8.0.3
  restart_app: ^1.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  time_machine: ^0.9.17
  bottom_picker: ^2.7.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.3
  table_calendar: ^3.0.9
  flutter_timezone: ^1.0.8
  package_info_plus: ^8.0.0
  flex_color_picker: ^3.4.1
  isar_flutter_libs: ^3.1.0+1
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.1.0

  # productivity app
  firebase_auth:
  firebase_core:
  cloud_firestore:
  flutter_dnd:
  flutter_switch:
  flutter_inset_box_shadow:
  hive_flutter:
  flutter_slidable:
  flutter_heatmap_calendar:
  # intl:
  shared_preferences:
  animated_snack_bar:
  google_generative_ai:
  # table_calendar:
  flutter_staggered_grid_view:
  sqflite:
  image_picker: ^1.1.1
  hive: ^2.2.3
  pedometer: ^4.0.1
  # path:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
