// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHiJwqWNpTj076KEaKIWYO0k-KsKtkJcU',
    appId: '1:8518523423:web:790099f7b655613f25132a',
    messagingSenderId: '8518523423',
    projectId: 'productivity-app-3f646',
    authDomain: 'productivity-app-3f646.firebaseapp.com',
    storageBucket: 'productivity-app-3f646.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKM0nwqbrWzeVTzBLyXHccforhrvVQNc',
    appId: '1:8518523423:android:b31a64a8f8e283b725132a',
    messagingSenderId: '8518523423',
    projectId: 'productivity-app-3f646',
    storageBucket: 'productivity-app-3f646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk0PPs2pdu0MrZTqCQ1AznHTWH6ZkgNUk',
    appId: '1:8518523423:ios:e7a9e0c5b06ee1b625132a',
    messagingSenderId: '8518523423',
    projectId: 'productivity-app-3f646',
    storageBucket: 'productivity-app-3f646.appspot.com',
    iosBundleId: 'com.example.productivityApp',
  );
}
